### ISSUE TITLE
ssd300训练

### ISSUE THREAD

**Issue by bixiaopeng0** [jiangzhubo/Follow_Bobo_AI_Sharing#2]
将训练数据resize为300x300，如果输入数据不是方形，resize之后图像会变形，然后我分别用方形数据和原始数据作为训练数据，发现将原始图像（不是方形）作为训练数据的效果要好一些，但是我想不明白，为什么这样效果更好？

**Comment by jiangzhubo** [comment]
你resize 后相当于改变了数据的形状，进而改变了数据特征，所以原始图像作为训练数据更好吧

**Comment by bixiaopeng0** [comment]
嗯呢，我昨天想通了，在测试的时候需要输入300x300，训练数据过程用原始数据就可以了，然后相应的进行crop，等比例缩小，图像是不会变形的
